version: '3'
services:
  app:
    restart: always
    build: ./app
    expose:
      - "8000"
    depends_on:
      - db
    command: gunicorn core.wsgi -b 0.0.0.0:8000 --reload
    volumes:
      - ./app/core:/usr/src/app
      - ./app/static/:/usr/src/app/static
  nginx:
    restart: always
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./app/static/:/usr/src/app/static
    depends_on:
      - app
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "33060:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
